#server:
#  port: 11420
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.24.128:3230/ip_test
#    #It is generally referred to root
#    username: root
#
#    #Your password
#    password: 1234567890
#  redis:
#    host: 192.168.24.128
#    #spring.redis.database: 0：指定连接Redis时使用的数据库，默认为0。
#    database: 0
#    #spring.redis.port: 6379：指定Redis服务器的端口号，默认为6379。
#    port: 6380
#    lettuce:
#      pool:
#        #spring.redis.lettuce.pool.max-idle: 8：指定连接池中的最大空闲连接数，默认为8。
#        max-idle: 8
#        #spring.redis.lettuce.pool.min-idle: 0：指定连接池中的最小空闲连接数，默认为0。
#        min-idle: 0
#        #spring.redis.lettuce.pool.max-active: 8：指定连接池中的最大活动连接数，默认为8。
#        max-active: 8
#        #spring.redis.lettuce.pool.max-wait: -1ms：指定从连接池中获取连接时的最大等待时间，默认为-1ms，表示无限等待。
#        max-wait: -1ms
#        #spring.redis.timeout: 180：指定与Redis服务器建立连接的超时时间，单位为秒，默认为180秒。
#    timeout: 180
#    session:
#      #session存储方式:session
#      store-type: redis
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.bloducspauter.base.entities;
